name = "EvoLP"
uuid = "71f1f4bb-392f-41f8-8452-d535d061e0f4"
authors = ["Xavier Sánchez Díaz <5231167+saxarona@users.noreply.github.com>"]
version = "1.0.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NamedTupleTools = "d9ec5142-1e00-5aa0-9d6a-321866360f50"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
Distributions = "0.25"
Documenter = "0.27"
julia = "1.8"
NamedTupleTools = "0.14"
OrderedCollections = "1.6"
StableRNGs = "1.0"
StatsBase = "0.33"
